import type { User, Ticket } from '../types'

export const DEMO_USERS: User[] = [
  { id: 'u1', name: 'Max Mustermann', email: 'max@h3x.io', role: 'admin' },
  { id: 'u2', name: 'Anna Schmidt', email: 'anna@h3x.io', role: 'agent' },
  { id: 'u3', name: 'Tobias Müller', email: 'tobias@h3x.io', role: 'agent' },
  { id: 'u4', name: 'Laura Weber', email: 'laura@h3x.io', role: 'user' },
  { id: 'u5', name: 'Klaus Fischer', email: 'Klaus@h3x.io', role: 'user' },
]

export const DEMO_TICKETS: Ticket[] = [
  {
    id: 't1',
    title: 'Login schlägt bei bestimmten Browser-Konfigurationen fehl',
    description: 'Einige Nutzer melden, dass der Anmeldevorgang in Firefox und Safari nicht funktioniert. Der Fehler tritt auf beim Klick auf den Login-Button. Console zeigt: "Uncaught TypeError: Cannot read property of undefined".',
    status: 'open',
    priority: 'critical',
    category: 'bug',
    createdById: 'u4',
    assignedToId: 'u2',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    tags: ['login', 'browser', 'frontend'],
    comments: [
      {
        id: 'c1',
        ticketId: 't1',
        authorId: 'u2',
        content: 'Ich habe das Problem reproduziert. Es liegt an einem inkompatiblen CSS-Override in der Theme-Datei. Arbeite an einem Fix.',
        createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        isInternal: false,
      },
    ],
  },
  {
    id: 't2',
    title: 'Dark Mode für das Dashboard implementieren',
    description: 'Nutzer wünschen sich einen Dark Mode für das Dashboard. Es sollte systemweite Präferenz respektieren und manuell umschaltbar sein.',
    status: 'in_progress',
    priority: 'medium',
    category: 'feature',
    createdById: 'u5',
    assignedToId: 'u3',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    tags: ['ui', 'dark-mode', 'dashboard'],
    comments: [],
  },
  {
    id: 't3',
    title: 'E-Mail Benachrichtigungen werden nicht zugestellt',
    description: 'Seit dem letzten Deployment werden keine Benachrichtigungs-E-Mails mehr versendet. Betrifft Passwort-Reset und Ticket-Updates.',
    status: 'open',
    priority: 'high',
    category: 'bug',
    createdById: 'u4',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    tags: ['email', 'notifications', 'backend'],
    comments: [],
  },
  {
    id: 't4',
    title: 'Datenbankabfragen optimieren für Reports',
    description: 'Die Report-Seite lädt sehr langsam (>10 Sekunden). Die Abfragen sind nicht optimiert und es fehlen Indizes auf häufig gefilterten Spalten.',
    status: 'in_progress',
    priority: 'high',
    category: 'performance',
    createdById: 'u2',
    assignedToId: 'u2',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    tags: ['database', 'performance', 'reports'],
    comments: [
      {
        id: 'c2',
        ticketId: 't4',
        authorId: 'u2',
        content: 'Erste Analyse abgeschlossen. Compound Indexes für (user_id, created_at) würden die Performance um ca. 80% verbessern.',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
        isInternal: true,
      },
    ],
  },
  {
    id: 't5',
    title: 'API-Endpunkt für Bulk-Import benötigt',
    description: 'Für den Import größerer Datenmengen benötigen wir einen dedizierten Bulk-Import API-Endpunkt mit CSV-Support und Validierungsrückmeldung.',
    status: 'open',
    priority: 'medium',
    category: 'feature',
    createdById: 'u5',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    tags: ['api', 'import', 'backend'],
    comments: [],
  },
  {
    id: 't6',
    title: 'XSS-Schwachstelle im Kommentarfeld',
    description: 'Im Kommentarfeld werden HTML-Tags nicht korrekt escaped. Ein Angreifer könnte JavaScript einschleusen.',
    status: 'resolved',
    priority: 'critical',
    category: 'security',
    createdById: 'u2',
    assignedToId: 'u1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    tags: ['security', 'xss', 'kommentare'],
    comments: [
      {
        id: 'c3',
        ticketId: 't6',
        authorId: 'u1',
        content: 'Fix deployed. Alle Kommentare werden nun durch DOMPurify sanitized.',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
        isInternal: false,
      },
    ],
  },
  {
    id: 't7',
    title: 'Passwort-Reset Link funktioniert nicht',
    description: 'Nutzer berichten, dass der Passwort-Reset Link nach dem Anklicken eine 404-Seite zeigt.',
    status: 'closed',
    priority: 'high',
    category: 'support',
    createdById: 'u4',
    assignedToId: 'u2',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 180).toISOString(),
    tags: ['auth', 'password-reset'],
    comments: [],
  },
  {
    id: 't8',
    title: 'Datei-Upload Größenlimit erhöhen',
    description: 'Das aktuelle Limit von 5MB ist für viele Nutzerfälle zu niedrig. Es wird ein Limit von mindestens 25MB benötigt.',
    status: 'open',
    priority: 'low',
    category: 'feature',
    createdById: 'u5',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    tags: ['upload', 'limits'],
    comments: [],
  },
]
